#!/bin/sh
set -e
WORDS=/usr/share/dict/words
head -n 1000 <${WORDS} >_words1000
seq 100 | random > _rand100

perf() {
    alg=$1
    hash=$2
    opts=$3
    map=
    mapopt=
    if [ x$alg = xbdz ]; then
        map="_words1000.map"
        mapopt="-m $map"
    fi
    if [ x$opts = x-I ]; then
        if [ x$alg = xbdz ]; then
            map="_rand100.map"
            mapopt="-m $map"
        fi
	echo nbperf $opts -a $alg
	./nbperf $opts -a $alg -o _test_int$alg.c $mapopt _rand100
	cc -g -I. -Wall -Wextra -D_INTKEYS -D$alg _test_int$alg.c test_main.c -o _test_int$alg && \
            ./_test_int$alg _rand100
    elif [ -z $hash ]; then
	echo nbperf $opts -a $alg
	./nbperf $opts -a $alg -o _test_$alg.c $mapopt _words1000
	cc -g -I. -Wall -Wextra -D$alg _test_$alg.c test_main.c mi_vector_hash.c -o _test_$alg && \
            ./_test_$alg _words1000
    else
	echo nbperf $opts -a $alg -h $hash
	./nbperf $opts -a $alg -h $hash -o _test_${alg}_${hash}.c $mapopt _words1000
	cc -g -I. -Wall -Wextra -D$alg -Dh_$hash _test_${alg}_${hash}.c test_main.c -o _test_${alg}_${hash} && \
            ./_test_${alg}_${hash} _words1000
    fi
}

perf chm
perf chm3
perf bdz
perf chm wyhash
perf chm3 wyhash
perf bdz wyhash
perf chm fnv
perf chm fnv3
perf chm3 fnv3
perf bdz fnv3 -f
#perf chm crc
perf chm wyhash -f
perf chm3 wyhash -f
perf bdz wyhash -f
perf chm wyhash -fp
perf chm3 wyhash -fp
perf bdz wyhash -fp
perf chm wyhash -p
perf chm3 wyhash -p
perf bdz wyhash -p
#perf chm wyhash -fps
#perf chm3 wyhash -fps
#perf bdz wyhash -fps
#perf chm wyhash -fs
#perf chm3 wyhash -fs
#perf bdz wyhash -fs

perf chm "" -I
#perf chm3 "" -I
#perf bdz "" -I
